trigger:
  branches:
    include:
    - master
  paths:
    include:
    - 'api/*'

pool:
  vmImage: 'vs2017-win2016'

displayName: 'Api'

steps:
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
    projects: |
      '**/Api.csproj'
    arguments: --output publish_output --configuration Release

- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/publish_output'
    includeRootFolder: false
    archiveType: zip
    archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1

